function fis = GenRandomFisController()
fis = sugfis();
%% E Premise
fis = addInput(fis,[-1 1],'Name','E');
m = sort(-1+2*rand(1,3));
sigma = -1+2*rand(1,3);
fis = addMF(fis,'E','gaussmf',[sigma(1,1), m(1,1)],'Name','N');
fis = addMF(fis,'E','gaussmf',[sigma(1,3), m(1,3)],'Name','Z');
fis = addMF(fis,'E','gaussmf',[sigma(1,2), m(1,2)],'Name','P');

%% delE Premise
fis = addInput(fis,[-1 1],'Name','delE');
m = sort(-1+2*rand(1,3));
sigma = -1+2*rand(1,3);
fis = addMF(fis,'delE','gaussmf',[sigma(1,1), m(1,1)],'Name','N');
fis = addMF(fis,'delE','gaussmf',[sigma(1,2), m(1,2)],'Name','Z');
fis = addMF(fis,'delE','gaussmf',[sigma(1,3), m(1,3)],'Name','P');

%% Drag Premise
fis = addInput(fis,[-1 1],'Name','C');
m = sort(-1+2*rand(1,3));
sigma = -1+2*rand(1,3);
fis = addMF(fis,'C','gaussmf',[sigma(1,1), m(1,1)],'Name','N');
fis = addMF(fis,'C','gaussmf',[sigma(1,2), m(1,2)],'Name','Z');
fis = addMF(fis,'C','gaussmf',[sigma(1,3), m(1,3)],'Name','P');
%% Force Q
fis = addOutput(fis,[-1 1],'Name','U');
Uvalues = rand(1,27); % There are 27 poss Rules
for i = 1 : length(Uvalues)
    fis = addMF(fis,'U','constant',Uvalues(1,i),'Name',['U',num2str(i-1)]);
end
rules = [...
    "E==N & delE==N & C==N => U=U0"; ...
    "E==N & delE==N & C==Z => U=U1"; ...
    "E==N & delE==N & C==P => U=U2"; ...
    "E==N & delE==Z & C==N => U=U3"; ...
    "E==N & delE==Z & C==Z => U=U4"; ...
    "E==N & delE==Z & C==P => U=U5"; ...
    "E==N & delE==P & C==N => U=U6"; ...
    "E==N & delE==P & C==Z => U=U7"; ...
    "E==N & delE==P & C==P => U=U8"; ...
    "E==Z & delE==N & C==N => U=U9"; ...
    "E==Z & delE==N & C==Z => U=U10"; ...
    "E==Z & delE==N & C==P => U=U11"; ...
    "E==Z & delE==Z & C==N => U=U12"; ...
    "E==Z & delE==Z & C==Z => U=U13"; ...
    "E==Z & delE==Z & C==P => U=U14"; ...
    "E==Z & delE==P & C==N => U=U15"; ...
    "E==Z & delE==P & C==Z => U=U16"; ...
    "E==Z & delE==P & C==P => U=U17"; ...
    "E==P & delE==N & C==N => U=U18"; ...
    "E==P & delE==N & C==Z => U=U19"; ...
    "E==P & delE==N & C==P => U=U20"; ...
    "E==P & delE==Z & C==N => U=U21"; ...
    "E==P & delE==Z & C==Z => U=U22"; ...
    "E==P & delE==Z & C==P => U=U23"; ...
    "E==P & delE==P & C==N => U=U24"; ...
    "E==P & delE==P & C==Z => U=U25"; ...
    "E==P & delE==P & C==P => U=U26"; ...
    ];
fis = addRule(fis,rules);

end